### ISSUE TITLE
質問です。

### ISSUE THREAD

**Issue by yoshitokun** [narache/kindle_comic_store#1]
こんにちは。
このようなエラーが発生し、kindle unlimitedのページでs-results-list-atfを探してみましたが見つかりませんでした。
仕様変更されたのですかね？

C:\Users\Administrator\Archive\kindle_comic_store-master\kindle_comic_store-mast
er>python store_kindle_book_info.py

DevTools listening on ws://127.0.0.1:55868/devtools/browser/963d608b-0e78-48a4-8
6d2-aa6adb503860
1ページ目の処理を開始しました。
Traceback (most recent call last):
  File "store_kindle_book_info.py", line 52, in <module>
    books = driver.find_element_by_id('s-results-list-atf').find_elements_by_tag
_name('li')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id

    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-p
ackages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"id","selector":"s-results-list-atf"}
  (Session info: headless chrome=74.0.3729.169)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d287
4a),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by narache** [comment]
ご報告ありがとうございます。
はい。作ってから知りましたがAmazonさんはすぐにデザイン変更してしまいます。
(使う人は居ないと思ってほったらかしていました・・・)
取り急ぎコードを最新化しましたがよくAmazon側がタイムアウトするので、期待せずゆるーくお使いいただければと。

**Comment by yoshitokun** [comment]
迅速なご対応ありがとうございます。
ばっちり動作しました！

**Comment by narache** [comment]
良かったです、ご確認ありがとうございました。
